/* tslint:disable */
/* eslint-disable */
/**
 * Github Search API
 * Github Search API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Repository
 */
export interface Repository {
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'owner': string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'stars': string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'description': string | null;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'url': string;
}
/**
 * 
 * @export
 * @interface SearchBody
 */
export interface SearchBody {
    /**
     * 
     * @type {string}
     * @memberof SearchBody
     */
    'search_text': string;
}
/**
 * @type SearchResultList
 * @export
 */
export type SearchResultList = Repository | User;

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'avatar_url': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'location': string | null;
}

/**
 * SearchApi - axios parameter creator
 * @export
 */
export const SearchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ApiSearchCreateSearchTypeEnum} searchType Search type  * &#x60;users&#x60; - Users * &#x60;repositories&#x60; - Repositories
         * @param {SearchBody} searchBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSearchCreate: async (searchType: ApiSearchCreateSearchTypeEnum, searchBody: SearchBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchType' is not null or undefined
            assertParamExists('apiSearchCreate', 'searchType', searchType)
            // verify required parameter 'searchBody' is not null or undefined
            assertParamExists('apiSearchCreate', 'searchBody', searchBody)
            const localVarPath = `/api/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication cookieAuth required

            if (searchType !== undefined) {
                localVarQueryParameter['search_type'] = searchType;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SearchApi - functional programming interface
 * @export
 */
export const SearchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SearchApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ApiSearchCreateSearchTypeEnum} searchType Search type  * &#x60;users&#x60; - Users * &#x60;repositories&#x60; - Repositories
         * @param {SearchBody} searchBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSearchCreate(searchType: ApiSearchCreateSearchTypeEnum, searchBody: SearchBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SearchResultList>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSearchCreate(searchType, searchBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.apiSearchCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SearchApi - factory interface
 * @export
 */
export const SearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SearchApiFp(configuration)
    return {
        /**
         * 
         * @param {ApiSearchCreateSearchTypeEnum} searchType Search type  * &#x60;users&#x60; - Users * &#x60;repositories&#x60; - Repositories
         * @param {SearchBody} searchBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSearchCreate(searchType: ApiSearchCreateSearchTypeEnum, searchBody: SearchBody, options?: RawAxiosRequestConfig): AxiosPromise<Array<SearchResultList>> {
            return localVarFp.apiSearchCreate(searchType, searchBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SearchApi - object-oriented interface
 * @export
 * @class SearchApi
 * @extends {BaseAPI}
 */
export class SearchApi extends BaseAPI {
    /**
     * 
     * @param {ApiSearchCreateSearchTypeEnum} searchType Search type  * &#x60;users&#x60; - Users * &#x60;repositories&#x60; - Repositories
     * @param {SearchBody} searchBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApi
     */
    public apiSearchCreate(searchType: ApiSearchCreateSearchTypeEnum, searchBody: SearchBody, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).apiSearchCreate(searchType, searchBody, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ApiSearchCreateSearchTypeEnum = {
    Users: 'users',
    Repositories: 'repositories'
} as const;
export type ApiSearchCreateSearchTypeEnum = typeof ApiSearchCreateSearchTypeEnum[keyof typeof ApiSearchCreateSearchTypeEnum];


